<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Quality Evaluation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for quality evaluation
    | components and messages.
    |
    */

    // Page titles and headers
    'quality_control_evaluation' => 'Quality Control Evaluation',
    'quality_control_scoring' => 'Quality Control Scoring',
    'evaluation_details' => 'Evaluation Details',
    'evaluation_summary' => 'Evaluation Summary',

    // Form labels and descriptions
    'complete_evaluation_description' => 'Complete the evaluation by scoring each item. The total score is calculated based on weighted percentages.',
    'evaluation_title' => 'Evaluation Title',
    'country' => 'Country',
    'select_country' => 'Select Country',
    'search_countries' => 'Search countries...',
    'country_required' => 'Please select a country',
    'brand' => 'Brand',
    'select_brand' => 'Select Brand',
    'search_brands' => 'Search brands...',
    'brand_required' => 'Please select a brand',
    'branch' => 'Branch',
    'select_branch' => 'Select Branch',
    'search_branches' => 'Search branches...',
    'branch_required' => 'Please select a branch',
    'branch_cannot_be_changed' => 'Branch cannot be changed for checklist evaluations',
    'selected_branch' => 'Selected Branch',
    'comments' => 'Comments',
    'additional_comments' => 'Additional Comments',
    'optional_comments' => 'Optional comments about this evaluation',
    'extra_points' => 'Extra Points',
    'bonus_penalty_points' => 'Bonus/Penalty Points',
    'extra_points_description' => 'Add or subtract points from the calculated score (-5 to +5)',

    // Progress and status
    'progress' => 'Progress',
    'items_completed' => 'items completed',
    'status' => 'Status',
    'draft' => 'Draft',
    'completed' => 'Completed',
    'total_score' => 'Total Score',

    // Actions
    'save_draft' => 'Save as Draft',
    'complete_evaluation' => 'Complete Evaluation',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'view' => 'View',
    'create_new' => 'Create New Evaluation',
    'back_to_list' => 'Back to Evaluations',

    // Score ranges and quality indicators
    'excellent_quality' => 'Excellent Quality',
    'good_quality' => 'Good Quality',
    'acceptable_quality' => 'Acceptable Quality',
    'needs_improvement' => 'Needs Improvement',

    // Statistics
    'total_evaluations' => 'Total Evaluations',
    'completed_evaluations' => 'Completed',
    'draft_evaluations' => 'Drafts',
    'average_score' => 'Average Score',

    // Validation messages
    'score_required' => 'Score is required',
    'score_must_be_number' => 'Score must be a number',
    'score_cannot_exceed_max' => 'Score cannot exceed maximum value',

    // Confirmation messages
    'delete_confirmation' => 'Are you sure you want to delete this evaluation?',
    'delete_warning' => 'This action cannot be undone.',
    'confirm_delete' => 'Yes, Delete',
    'cancel' => 'Cancel',

    // Success messages
    'evaluation_created' => 'Evaluation created successfully',
    'evaluation_updated' => 'Evaluation updated successfully',
    'evaluation_deleted' => 'Evaluation deleted successfully',

    // Additional translations for Show page
    'control_evaluation' => 'Control Evaluation',
    'base' => 'Base',
    'bonus_points_added' => 'bonus points added to final score',

    // PDF Export translations
    'export_pdf' => 'Export PDF',
    'download_pdf' => 'Download PDF',
    'regenerate_pdf' => 'Regenerate PDF',
    'exporting_pdf' => 'Exporting...',
    'pdf_export_success' => 'PDF exported successfully',
    'pdf_export_failed' => 'Failed to export PDF',
    'branch_visits_report' => 'Branch Visits Report / Quality Department',
    'branch_name' => 'Branch Name',
    'evaluation_month' => 'Evaluation Month',
    'evaluation_date' => 'Evaluation Date',
    'evaluation_status' => 'Evaluation Status',
    'evaluation_criteria' => 'Evaluation Criteria',
    'weight_percentage' => 'Weight %',
    'first_visit' => 'First Visit',
    'second_visit' => 'Second Visit',
    'third_visit' => 'Third Visit',
    'notes' => 'Notes',
    'excluded_from_score' => 'Excluded from Score',
    'base_score' => 'Base Score (before extra points)',
    'extra_points' => 'Extra Points',
    'final_score' => 'Final Score',
    'quality_monitor' => 'Quality Monitor',
    'branch_manager' => 'Branch Manager',
    'quality_manager' => 'Quality Manager',
    'signature' => 'Signature',
    'generated_by_system' => 'Generated by Quality Assurance System',

    // Checklist Template translations
    'loading_template' => 'Loading template...',
    'complete_checklist_description' => 'Please complete all required fields',
    'yes' => 'Yes',
    'no' => 'No',
    'not_applicable' => 'N/A',
    'one_point' => '1 PT',
    'half_point' => '0.5 PT',
    'zero_point' => '0 PT',
    'enter_response' => 'Enter your response',
    'field_required' => 'This field is required',
    'points' => 'points',
    'no_branches_available' => 'No branches are available for your access level. Please contact your administrator.',
    'complete_all_items' => 'Please complete all evaluation items to submit',
    'saving' => 'Saving...',
    'submitting' => 'Submitting...',
    'checklist_template' => 'Checklist Template',
    'sections' => 'Sections',
    'questions' => 'Questions',
    'not_answered' => 'Not Answered',
    'no_answer_provided' => 'No answer provided',
    'created' => 'Created',
    'completed_on' => 'Completed on',
    'items_evaluated' => 'Items Evaluated',
    'weighted_total' => 'Weighted Total',
    'performance' => 'Performance',
    'weighted_contribution' => 'Weighted Contribution',
    'achieved' => 'achieved',
    'excellent' => 'Excellent',
    'good' => 'Good',
    'fair' => 'Fair',
    'needs_improvement' => 'Needs Improvement',
    'no_actions_available' => 'No actions available based on your permissions.',
    'confirm_delete_title' => 'Confirm Delete',
    'confirm_delete_message' => 'Are you sure you want to delete this evaluation? This action cannot be undone.',
    'edit_evaluation' => 'Edit Evaluation',
    'create_new_evaluation' => 'Create New Evaluation',
    'delete_evaluation' => 'Delete Evaluation',
    'photo_documentation' => 'Photo Documentation',
    'photo_description' => 'Capture photos to document your evaluation findings',
    'photos_attached' => '{count} photo(s) attached',
    'checklist_score' => 'Checklist Score',
    'from' => 'from',

];
